### ISSUE TITLE
DBeaver crashes frequently on my Mac.

### ISSUE THREAD

**Issue by derekzhan** [dbeaver/dbeaver#39242]
### Description

<img width="440" height="458" alt="Image" src="https://github.com/user-attachments/assets/03cc2bef-7cf4-4a44-bb6f-5c8c466b07ac" />

This is crash log,  It crashes automatically every day, I'm going crazy! can you help me ?, thanks.

[dbeaver crash.log](https://github.com/user-attachments/files/22435584/dbeaver.crash.log)

### DBeaver Version

Version 25.2.0.202508311659

### Operating System

Version 26.0 macos Apple M4

**Comment by ShadelessFox** [comment]
Seems like a duplicate of #37873

> It crashes automatically every day

We definitely didn't program DBeaver to crash every day :^)

Something is causing DBeaver to crash. Have you noticed any pattern? Like opening a SQL editor, etc?

**Comment by derekzhan** [comment]
It crashes when I edit long JSON fields. 

<img width="480" height="237" alt="Image" src="https://github.com/user-attachments/assets/c468e6cd-d75c-4420-b7b7-04312e6b9c71" />

**Comment by ShadelessFox** [comment]
Any particular steps?

**Comment by derekzhan** [comment]
Yeah, it crashes every time I run an update like this SQL below.
`--  Auto-generated SQL script. Actual values for binary/complex data types may differ - what you see is the default string representation of values.
UPDATE xxxxx.xxxtable
	SET additional_info='{
  "faq": "<p><span style=\\"font-weight: bold;\\">xxxxxxxxxxxxxxxxxxxx.&nbsp;&nbsp;</span><br></p><p>Examples:</p><p>xxxxxxxxxxxxx?</p><p>- xxxxxxxxxxxxx&nbsp;xxxxxx</p><p></p><p>2. Ixxxxxxxxxx.</p><p></p><p><br></p>",
  "logo": "https://xxxxxxxxxxxx.png",
  "terms": {
    "en": "<p><span style=\\"font-weight: bold;\\">xxxxxxxxxxx.</span></p><p>Examples:</p><p>1.&nbsp;xxxxxxxxxxxxxx.\\n\\n</p>",
    "fr": "",
    "zh": "<p><span style=\\"font-weight: bold;\\">xxxxxxxxxxxxxxxxx。</p>"
  },
  "youpi": {
    "product_id": xxxxxxx,
    "card_values": {
      "1000": {
        "value": "1050"
      }
    },
    "alipay_pass_template_id": "xxxxxxxxx"
  },
  "purchaseLimit": 6,
  "slogan": "",
  "privacy": "<p><span style=\\"font-weight: bold;\\">xxxxxxxxxxx.&nbsp;&nbsp;</span><br></p><p>Examples:<span style=\\"font-weight: bold;\\"><br></span></p><p>xxxxxxxx.&nbsp;&nbsp;<br></p><p>xxxxxxxxxxxxx\\n\\n</p><p></p><p></p><p></p>",
  "brandName": "xxxxxxxx",
  "cardCover": [
    {
      "url": "https://xxxxx.png",
      "name": "0"
    },
    {
      "url": "https://xxxxxxxxxx.png",
      "name": "1"
    }
  ],
  "giftEnable": true,
  "instruction": {
    "en": "<p><span style=\\"font-weight: bold;\\">xxxxxxx.&nbsp;&nbsp;</span></p><p>Examples:<span style=\\"font-weight: bold; font-size: large;\\"><br></span></p><p>xxxxxxxx.</p><p>2. xxxxxxxxxxxxxxxxxxxxxxx.&nbsp;&nbsp;<br><br></p>",
    "fr": "",
    "zh": "<p><span style=\\"font-weight: bold;\\">xxxxx</span></p><p>xxxxxxxxxxxx</p><p>xxxxxx</p><p>2. xxxxxxxxxxxx&nbsp;</p>"
  },
  "shareSettings": {
    "shareImage": "",
    "shareTitle": "",
    "momentsText": "",
    "momentsImage": "",
    "miniProgramImage": "",
    "miniProgramTitle": ""
  },
  "serviceMessage": "<p><span style=\\"font-weight: bold;\\">xxxxxxxxxxxxxxxxxxxxxxxxxxx.\\n\\n<br></p><p><br></p>",
  "termsDirectlyDisplay": false
}'
	WHERE commodity_code_id=123123123123;
`

**Comment by ShadelessFox** [comment]
Interesting. Thank you. We haven't been able to reproduce the issue so far, but we are investigating.

**Comment by derekzhan** [comment]
> Interesting. Thank you. We haven't been able to reproduce the issue so far, but we are investigating.

When you edit manually and hit save, it crashes shortly after

**Comment by JamesInform** [comment]
I can second that on MacOS 15.7. Am not able to reproduce, but it crashed multiple time when executing sql statements in the sql editor via keyboard shortcut (ctrl+return).

The crash was immediate and the application vanished from screen ... no error dialog or message after starting dbeaver again.

I also encountered that the sql editor's content was not saved.

Strange

**Comment by wouterj** [comment]
I experience this as well since updating to 25.2.1 (not sure what my previous version was). With the JSON value window open, dbeaver crashes frequently: on editing the field, on refreshing the table, etc.

**Comment by JDavidMares** [comment]
Hello!
I have the same issue since update to macOS Tahoe 26, I was using the last version from DBeaver 25.2.3, I tried with older versions, 25.1.2, 25.0.5 and 24.2.3 and It was the same.
On my side, the issue occurs when I try to open it on full screen or when I try to right click on a row from any query result.
The logs I have been able to obtain are these:

```
Swift/UnsafePointer.swift:1104: Fatal error: UnsafeMutablePointer.initialize overlapping range

A fatal error has been detected by the Java Runtime Environment:

SIGILL (0x4) at pc=0x00007ff81ca30931, pid=19138, tid=259

JRE version: OpenJDK Runtime Environment Temurin-21.0.5+11 (21.0.5+11) (build 21.0.5+11-LTS)
Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (21.0.5+11-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
Problematic frame:
C  [libswiftCore.dylib+0x117931]  $ss17_assertionFailure__4file4line5flagss5NeverOs12StaticStringV_A2HSus6UInt32VtF+0x1c1
```

Also tried adding this 2 flags to ini file, but also is failing:
```
-Dswt.disableFullscreenMode=true
-Dswt.renderer=none
```

**Comment by E1izabeth** [comment]
According to the crash report, the issue is the same as in #35767 #37873

**Comment by IvanGorshechnikov** [comment]
Unfortunately, we can't reproduce your issue.
Is it still reproducible in the latest DBeaver version?

**Comment by davestokes** [comment]
@derekzhan Is this problem still reproducible with 26.0.3?
