### ISSUE TITLE
(Grid) display

### ISSUE THREAD

**Issue by gab444** [dbeaver/dbeaver#9600]
#### System information: 
- OS: Win - 10 
- DBeaver version - 7.1.5
- Additional extensions

#### Connection specification:
- Generic JDBC 

#### Describe the problem you're observing:
after upgrading to 7.1.5, sql query result grid display is not visible. works well under th eText mode. 
#### Include any warning/errors/backtraces from the logs
Message : Unhandled event loop exception:

java.lang.NoSuchMethodError: org.eclipse.swt.graphics.FontMetrics.getAverageCharacterWidth()D
	at org.jkiss.dbeaver.ui.UITextUtils.getShortString(UITextUtils.java:102)
	at org.jkiss.dbeaver.ui.controls.lightgrid.GridColumnRenderer.paint(GridColumnRenderer.java:139)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintColumnsHeader(LightGrid.java:2517)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintColumnHeader(LightGrid.java:2504)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.paintHeader(LightGrid.java:2473)
	at org.jkiss.dbeaver.ui.controls.lightgrid.LightGrid.onPaint(LightGrid.java:2219)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:231)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1593)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4856)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5123)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3822)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at com.compuware.frameworks.workbench.Application.start(Application.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by kseniiaguzeeva** [comment]
Unfortunately I cannot reproduce. Do you use any type of Theme? Is it standalone or Eclipse DBeaver?

**Comment by kseniiaguzeeva** [comment]
@gab444 Could you please report if the bug can be reproduced in 7.2.0 (release 31.08.20)?

**Comment by gab444** [comment]
@kseniiaguzeeva : once the plugin is available to upgrade in eclipse, I will upgrade and provide an update

**Comment by gab444** [comment]
@kseniiaguzeeva : verified the issue, its fixed. thanks.

**Comment by kseniiaguzeeva** [comment]
Thank you for testing!
