### ISSUE TITLE
Redshift drivers no longer working after latest install of DBeaver

### ISSUE THREAD

**Issue by will-harrison-kindred** [dbeaver/dbeaver#39687]
### Description

 Version 25.2.5.202511161745
Release date: November 17, 2025
© 2025 DBeaver Corp
https://dbeaver.io/

Error:  
Exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper [in thread "Redshift JDBC driver connection thread"]

<< Details                                                                OK

Something unusual has occurred to cause the driver to fail. Please report this exception.

Class definition not found: Could not initialize class com.amazon.redshift.core.v3.QueryExecutorImpl

Exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper [in thread "Redshift JDBC driver connection thread"]

### DBeaver Version

25.2.5.202511161745

### Operating System

Windows 11

**Comment by alejandrofm** [comment]
Temporary fix, rolling back to Driver version 2.0.0.3

**Comment by micheal-icp** [comment]
Having same issue. After updating on my Mac to v25.2.5.202511161745, which forces a new driver update on Redshift, I get the following error:

<img width="640" height="237" alt="Image" src="https://github.com/user-attachments/assets/77031ea3-50de-4ddc-bc12-30ccfddc404d" />


Using MacOS Tahoe, v26.1.

**Comment by micheal-icp** [comment]
Rolling back to the Redshift driver v2.1.03 also works as a work-around.

For those needing to download a previous version, here's AWS' previous versions link:

https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-previous-driver-version-20.html

**Comment by labanovichttps** [comment]
@will-harrison-kindred Thank you for your report. We'll investigate this issue.

**Comment by serge-rider** [comment]
Duplicate of https://github.com/dbeaver/dbeaver/issues/39681

**Comment by will-harrison-kindred** [comment]
Thank you for the workaround, rolling back the driver version. That worked :-)

**Comment by sduboulay** [comment]
Here's a fix I found and confirmed worked for me 

Fix: Add the Jackson JARs to the driver’s library folder in DBeaver
1. Go to:
DBeaver → Database → Driver Manager
2. Select your driver (Redshift? Trino? Athena?)
3. Click “Edit…”
4. Go to the Libraries tab
5. Click Add File… and add these 3 JARs:
You can download them from Maven Central (safe):
jackson-databind-2.xx.x.jar
jackson-core-2.xx.x.jar
jackson-annotations-2.xx.x.jar
Latest stable (as of late 2024):
https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.17.1/
Add all three JARs into the driver.
6. Restart DBeaver
Required because the classloader is initialized at startup.
