### ISSUE TITLE
Dbeaver 5.1.6 Exception [deepin linux]

### ISSUE THREAD

**Issue by hugorn** [dbeaver/dbeaver#4102]
After upgrade from 5.1.5 to 5.1.6 the app stop open:

2018-08-28 08:59:49.695 - DBeaver 5.1.6.201808262133 is starting
2018-08-28 08:59:49.697 - OS: Linux 4.15.0-29deepin-generic (amd64)
2018-08-28 08:59:49.697 - Java version: 9.0.1 by Oracle Corporation (64bit)
2018-08-28 08:59:49.698 - Install path: '/usr/share/dbeaver'
2018-08-28 08:59:49.698 - Instance path: 'file:/home/hugo/.dbeaver4/'
2018-08-28 08:59:49.698 - Memory available 64Mb/1024Mb
2018-08-28 08:59:49.746 - Starting RMI server at 58383
2018-08-28 08:59:49.872 - Run workbench
2018-08-28 08:59:49.964 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 25 more
2018-08-28 08:59:49.977 - DBeaver is stopping
2018-08-28 08:59:49.978 - null
java.lang.IllegalStateException: Workbench has not been created yet.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.shutdown(DBeaverApplication.java:286)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by webjoel** [comment]
Same problem here: Linux Ubuntu 16.04 x64.

I Reverted to 5.1.5

**Comment by serge-rider** [comment]
@hugorn What DBeaver distribution do you use (deb, zip)?
@webjoel Potentially this might be related to #3980 but error message itself has nothing to do with GTK.

This looks like a typical problem with Java 9 (missing modules). But we didn't make any changes in configuration.
You could check that dbeaver.ini contains line `--add-modules=ALL-SYSTEM` (it is required for Java9 compatibility).

**Comment by webjoel** [comment]
@serge-rider deb distribution, Java 8 here.

**Comment by webjoel** [comment]
@serge-rider I tested open dbeaver directally on folder installation and works fine, but in icon desktop not.

**Comment by hugorn** [comment]
@serge-rider I usually use the .deb version, im my distro the version 5.1.6 works only with root privileges.

**Comment by webjoel** [comment]
@serge-rider See:

- /usr/share/applications/dbeaver.desktop:

```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Name=DBeaver Community
GenericName=UniversaL Database Manager
Comment=Universal Database Manager and SQL Client.
Path=/usr/share/dbeaver/
Exec=/usr/share/dbeaver/dbeaver
Icon=/usr/share/dbeaver/dbeaver.png
Categories=IDE;Development
WM_CLASS=DBeaver Community
StartupWMClass=DBeaver Community
StartupNotify=true
Keywords=Database;SQL;IDE;JDBC;ODBC;MySQL;PostgreSQL
MimeType=application/sql
```
- No dbeaver log contains, only syslog:

```
Aug 29 14:17:18 coleiro gnome-session[3381]: (gnome-software:3602): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/dbeaver.desktop.dpkg-new file: cannot process file of type text/plain
Aug 29 14:17:19 coleiro gnome-session[3381]: (gnome-software:3602): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/dbeaver.desktop file: cannot process file of type application/x-desktop
Aug 29 14:17:19 coleiro gnome-session[3381]: (gnome-software:3602): As-WARNING **: failed to rescan: Failed to parse /usr/share/applications/bamf-2.index file: cannot process file of type text/plain
```

**Comment by hugorn** [comment]
@serge-rider 
hugo@hugo-PC:~/Downloads$ sudo dpkg -i dbeaver-ce_5.1.6_amd64.deb 
[sudo] senha para hugo: 
(Lendo banco de dados ... 315625 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar dbeaver-ce_5.1.6_amd64.deb ...
A descompactar dbeaver-ce (5.1.6) sobre (5.1.6) ...
Configurando dbeaver-ce (5.1.6) ...
A processar 'triggers' para lastore-daemon (0.9.66-1) ...
A processar 'triggers' para desktop-file-utils (0.23-3) ...
A processar 'triggers' para bamfdaemon (0.5.3-2+b1) ...
Rebuilding /usr/share/applications/bamf-2.index...
A processar 'triggers' para mime-support (3.60) ...
hugo@hugo-PC:~/Downloads$ dbeaver
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp

(java:8882): Gtk-WARNING **: 15:39:03.932: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",

(java:8882): Gtk-WARNING **: 15:39:03.932: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",
2018-08-30 15:39:05.118 - Create display
2018-08-30 15:39:05.233 - DBeaver 5.1.6.201808262133 is starting
2018-08-30 15:39:05.235 - OS: Linux 4.15.0-29deepin-generic (amd64)
2018-08-30 15:39:05.235 - Java version: 9.0.1 by Oracle Corporation (64bit)
2018-08-30 15:39:05.235 - Install path: '/usr/share/dbeaver'
2018-08-30 15:39:05.236 - Instance path: 'file:/home/hugo/.dbeaver4/'
2018-08-30 15:39:05.236 - Memory available 77Mb/1024Mb
2018-08-30 15:39:05.248 - Starting RMI server at 64568
2018-08-30 15:39:05.327 - Run workbench
2018-08-30 15:39:05.388 - Internal error in workbench lifecycle
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:410)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:491)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:505)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:204)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:614)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:156)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 25 more
2018-08-30 15:39:05.395 - DBeaver is stopping
2018-08-30 15:39:05.395 - null
java.lang.IllegalStateException: Workbench has not been created yet.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:93)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.shutdown(DBeaverApplication.java:286)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

(dbeaver:8846): Gtk-WARNING **: 15:39:06.124: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",

(dbeaver:8846): Gtk-WARNING **: 15:39:06.124: Não foi possível localizar a ferramenta de temas no module_path: "adwaita",

**Comment by serge-rider** [comment]
@webjoel We had a few similar bug reports (desktop icon doesn't work).

Could you try to remove line 
`MimeType=application/sql`?

**Comment by serge-rider** [comment]
@hugorn This is definitely Java9 specific error.
Could you post contents of /usr/share/dbeaver/dbeaver.ini ?

**Comment by hugorn** [comment]
Tested with

launcher.GTK_version
2
-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.551.v20171108-1834
-showsplash
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m


and

-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.551.v20171108-1834
-showsplash
-vmargs
-XX:+IgnoreUnrecognizedVMOptions
--add-modules=ALL-SYSTEM
-Xms64m
-Xmx1024m

**Comment by webjoel** [comment]
@serge-rider I removed line and not works.

**Comment by serge-rider** [comment]
@webjoel :(
Well. I assume that .desktop file is the same for 5.1.5 as for 5.1.6 (at least it should be the same). So it can't be the problem. No clues so far.

PS I still can't reproduce this problem on any of my Ubuntus..

**Comment by webjoel** [comment]
@serge-rider I was with same problem in other version previous (not remember which), solution was remove complete version old dbeaver and install new version, but now this not works.

My installation of dbeaver 5.1.6 with problem is "https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb"

**Comment by serge-rider** [comment]
@hugorn Weird. Config is ok. Could you try to remove previous version completely (rm -rf /usr/share/dbeaver) and install it again? There should be file plugins/javax.annotation_1.2.0.v201602091430.jar in DBeaver installation.

**Comment by hugorn** [comment]
@serge-rider 15.1.6 Only works with root privileges.

![test](https://user-images.githubusercontent.com/9035153/44910509-d2e72d00-acf9-11e8-92b2-7c13f2e2def3.gif)

**Comment by serge-rider** [comment]
@webjoel Good

@hugorn I think you problem is the same as in #4163. Try to delete/rename folder `.dbeaver`  if it exists.

**Comment by hugorn** [comment]
> @webjoel Good
> 
> @hugorn I think you problem is the same as in #4163. Try to delete/rename folder `.dbeaver` if it exists.

@serge-rider 
I removed any existing dbeaver folder from my system, both the root user and the conventional user. After reinstallation versions 5.1.4 and 5.1.5
worked correctly, the error occurred from version 5.1.6 and above, which only work as root.

**Comment by serge-rider** [comment]
@hugorn That's very strange. Because 5.1.6 didn't have any changes in packaging. All I can suggest is to try 5.2.1 EA version (https://dbeaver.io/files/ea) - it contains the fix of #4163 bug.

**Comment by hugorn** [comment]
> @hugorn That's very strange. Because 5.1.6 didn't have any changes in packaging. All I can suggest is to try 5.2.1 EA version (https://dbeaver.io/files/ea) - it contains the fix of #4163 bug.
@serge-rider 

This solve the problem: https://bugs.eclipse.org/bugs/show_bug.cgi?id=493761#c107

unset _JAVA_OPTIONS

**Comment by serge-rider** [comment]
@hugorn Thanks for the info
