### ISSUE TITLE
Active Database cannot be chosen

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#7690]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 6.3.3

#### Connection specification:
- Database name and version Snowflake

#### Describe the problem you're observing:
Error appears when trying to change active database using pop-up (Ctrl+0)
![image](https://user-images.githubusercontent.com/31996417/72683450-89fb6880-3ae8-11ea-8fe1-7625be85716f.png)

**Comment by JamesInform** [comment]
More than this, on Mac I even don't have the context menu "Set Active" available in the navigator for PostgreSQL databases.

**Comment by serge-rider** [comment]
@JamesInform it is not related (you can change active schema in main toolbar/menu/shortcut).
See  comments about active schema in #7679 .
Set Active command was removed (and we don't have plans to return it back)

**Comment by idkw** [comment]
Please restore the old behavior with ctrl+shift+a to select the active schema, it is very cumbersome now

**Comment by herbinator** [comment]
> Set Active command was removed (and we don't have plans to return it back)
@serge-rider removing the set active command from right-click contect menu in the database navigator feels like removing simplicity.

**Comment by JamesInform** [comment]
@serge-rider 
Could you please rethink and maybe revert your decision concerning the removal of the "Set Active" command? Without it the productivity will drop noticeablely, at least on my site because I extensively use PostgreSQL with several databases where I often need to switch between databases to execute the same sql commands.

Btw. "(you can change active schema in the main toolbar/menu/by shortcuts)" isn't working in 6.3.4!

James

**Comment by serge-rider** [comment]
Please see #7693 for comments (this ticket is about Snowflake, it is very different).

@JamesInform If it doesn't work then it is a bug. Please write more details (error log/screenshot).

**Comment by serge-rider** [comment]
Fixed

**Comment by uslss** [comment]
verified

**Comment by timgilbert** [comment]
I'm not sure whether this issue might have regressed, but I'm seeing the same error when trying to set the active connection in a SQL editor when connected to Snowflake. I'm on DBeaver  7.2.3.202010181902 under macOS 10.14.6. The driver being used is snowflake-jdbc-3.12.14.jar, which is the latest one on maven as of this moment. The snowflake server is reported as 4.36.3 from "test connection".

Everything else related to Snowflake seems to work fine; "Test Connection" works and I can browse databases and schemas as usual, generate diagrams, preview data, etc. But selecting the schema gives me the same error box as in the description of this ticket, and I'm not sure what schema the queries are running in but they are unable to see the objects in the schema I'm looking for.

I've tried updating the schema in the connection settings and restarting DBeaver, but it hasn't changed the behavior.

Could somebody kindly re-test this bug please?

The error output I see when I hit the schema-selection button from the toolbar is as follows:

```
SQL Error [2043] [02000]: SQL compilation error:
Object does not exist, or operation cannot be performed.
SQL compilation error:
Object does not exist, or operation cannot be performed.
SQL compilation error:
Object does not exist, or operation cannot be performed.
```
